apiVersion: v1
kind: Pod
metadata:
  name: duckdns-pod
  labels:
    name: duckdns-pod
    app: duckdns
spec:
  containers:
    - name: duckdns
      image: linuxserver/duckdns
      env:
        - name: SUBDOMAINS
          value: "kr1ps.duckdns.org"
        - name: TOKEN
          value: "ec979d9a-d0a7-48ba-be3c-f74802e2ccbb"
        - name: TZ
          value: "America/Santo_Domingo"
        - name: LOG_FILE
          value: "false"
